### ISSUE TITLE
Translators need to be notified when this is published

### ISSUE THREAD

**Issue by phetsims** [phetsims/ohms-law#1]
In the process of converting this simulation to HTML5, one of the strings was changed from "current =" to simply "current".  Most translation files were edited in a way that probably fixed this, but some (Arabic and Hebrew for certain, and probably others) couldn't be easily changed.  Translators should be notified when this is published so that they can check and, if needed, fix any resultant errors.

**Comment by jbphet** [comment]
Our plan is to notify translators for all sims once the translation facility comes on line, so no need to track a separate issue for Ohm's Law.  Closing.
