### ISSUE TITLE
Change hint for Keyboard Shortcuts

### ISSUE THREAD

**Issue by terracoda** [phetsims/ohms-law#105]
@jessegreenberg, just tested [Ohm's Law dev 20](https://www.colorado.edu/physics/phet/dev/html/ohms-law/1.4.0-dev.20/phet/ohms-law_en_phet.html?accessibility)

Awesome implementation, and I have one change to the static descriptions which will be the same across all sims.

Change the **keyboard shortcut's hint** in the Scene Summary from:
- "If you need to, check out keyboard shortcuts for this sim."
To: 
- "If needed, check out keyboard shortcuts for this sim."

**Comment by jessegreenberg** [comment]
Done in the above commit, changed for sims that currently have a scene summary.
