### ISSUE TITLE
branch: compare-height

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ohms-law#106]
Identified by `print-branches.sh`. Please describe.

FYI, all non-release branches are supposed to have an associated GitHub issue. Title is of the form "branch: {{branchName}}}". The description should include: the purpose of the branch, expected lifetime of the branch, references to any related issues. The issue can be closed when the branch is deleted.

**Comment by pixelzoom** [comment]
Assigning to @jessegreenberg since he made the most recent commits in this branch.

**Comment by jessegreenberg** [comment]
This branch was for https://github.com/phetsims/ohms-law/issues/74 and is no longer relevant. Deleting.

**Comment by jbphet** [comment]
Reopening.  This branch was restored during an effort to recover some branches that were accidentally deleted.  This one had been _intentionally_ deleted, and now needs to be re-deleted.  See https://github.com/phetsims/special-ops/issues/198.

**Comment by jbphet** [comment]
Re-deletion complete.  Closing.
