### ISSUE TITLE
Larger Step Size with Pg Up and Pg Down

### ISSUE THREAD

**Issue by terracoda** [phetsims/ohms-law#109]
Question regarding pedagogically useful value for the Pg Up and Pg Down keys.

The default step size for V slider rounds to the nearest 0.5.
Should the larger step size round to 1.0?

The default step size for R slider rounds to the nearest 10.
Should the larger step size round to the nearest 100?

Or, maybe that is not how the larger step size works?

Just wondering how this is supposed work :-)

**Comment by jessegreenberg** [comment]
Default behavior for Page up/Page down for a typical HTML HSlider is to increment/decrement  the value  by 1/10th of the total range. We kept that for our custom slider approach. For the resistance slider, that turns out to be 99. For the voltage slider, that turns out to be 0.89.

But we can have a custom step size if necessary.

**Comment by terracoda** [comment]
@jessegreenberg, thanks for the explanation! I'll double check with @emily-phet to see if we need to customize the big steps.

**Comment by terracoda** [comment]
@emily-phet, could you comment about the big steps? Is it pedagogically important that the values round to  the nearest 1.0 for V slider and to the nearest 100 for the R sliders when taking big steps?

In fact, with this sim, the most relevant large step size for voltage would seem to be 1.5 volts, the amount of a full battery. That would, however, be less than 10 steps.

If you and @jessegreenberg have already discussed the big step size in detail, please just say so ;-), and I will close this issue.

**Comment by emily-phet** [comment]
@terracoda We went with the "increment by 1/10th" to align with standard slider pg up/pg down behavior. 
It's fine with me if we round that to 100 (for R) and 1 (for V) - if it's a very simple, quick thing to do. If it's not very simple/quick - let's leave it as is. 

I don't think 1.5 V is actually pedagogically important - it just happens to be a typical battery size (an interesting connection to make, but not a primary goal).

**Comment by terracoda** [comment]
@emily-phet, thanks. I was pretty sure this had been discussed. I'll check in with @jessegreenberg to see if the rounding is easy to do, and if not we will leave as is.

Thanks for clarification on the 1.5 volts.

**Comment by terracoda** [comment]
@jessegreenberg, could comment on the implementation time for rounding the big steps? If this would take a lot of time, we'll stick with the current un-rounded values of 1/10th the slider range.

**Comment by terracoda** [comment]
After discussing this more with @jessegreenberg in person, I think we are going to just stick with the default 1/10th the range for Pg Up/Pg Down. 

It is easy to round up or down with an Arrow key press after using Pg Up or Pg Down.

I am closing this issue.
