### ISSUE TITLE
How best to nest options in SliderUnit

### ISSUE THREAD

**Issue by zepumph** [phetsims/ohms-law#111]
It has been decided that we want nest options so it is easier to pass through options to a child, but @jessegreenberg @mbarlow12 and I are having a hard time figuring out to manage that with some options that we don't want to be overridable. 

So far we did converted this:

```js
  options = _.extend( {
      tandem: tandem,
      accessibleDecimalPlaces: 0,
      keyboardStep: 1,
      shiftKeyboardStep: 0.1,
      accessibleValuePattern: '{{value}}', // string pattern used for formating the value read by the screen reader
      endDrag: function() {}, // called at end of drag by HSlider
      startDrag: function() {}
    }, options );

```

to this:

```js
  options = _.extend( {
      tandem: tandem,

      hsliderOptions: null // filled in below
    }, options );

    // default options to be passed into hslider
    options.hsliderOptions = _.extend( {

      accessibleDecimalPlaces: 0,
      keyboardStep: 1,
      shiftKeyboardStep: 0.1,
      accessibleValuePattern: '{{value}}', // string pattern used for formating the value read by the screen reader
      endDrag: function() {}, // called at end of drag by HSlider
      startDrag: function() {}
    }, options.hsliderOptions );
```

Because most of the options for `SliderUnit` Above are just being passed into HSlider.

But we are having a hard time figuring out the convention of working that into some options that we don't want overwritable. Here is what `HSlider` currently looks like:

```js
  var slider = new HSlider( property, range, {
      trackFillEnabled: 'black',
      thumbFillEnabled: '#c3c4c5',
      thumbFillHighlighted: '#dedede',
      rotation: -Math.PI / 2,

      trackSize: new Dimension2( OhmsLawConstants.SLIDER_HEIGHT, 4 ),
      tandem: tandem.createTandem( 'slider' ),

      startDrag: options.startDrag,
      endDrag: options.endDrag,

      // a11y
      keyboardStep: options.keyboardStep,
      shiftKeyboardStep: options.shiftKeyboardStep,
      accessibleDecimalPlaces: options.accessibleDecimalPlaces,
      accessibleValuePattern: options.accessibleValuePattern,
      containerTagName: 'li',
      labelContent: labelContent,
      labelTagName: 'label'
    } );

```

Things like the `tandem` and `thumbFillEnabled` should not be set by the parent of `SliderUnit`, but we also don't want to have an assert line for each of these before the `options.hsliderOptions` extend call. How do we manage this?

**Comment by samreid** [comment]
Adding asserts is clear, fully general and works with our existing patterns.  It is wordy, but perhaps it is OK?

Also, I'm having trouble figuring out which of the options in the preceding examples are supposed to be non-overrideable, and what problem it would cause if they were overridebale.  Can you clarify?

**Comment by zepumph** [comment]
I guess my thought is that I didn't write slider unit, and I don't know how dangerous it is (necessarily) to open it up to overriding these defaults. Perhaps in most cases it would be alright, probably above any of them could be overridden by the client, but the pattern seems sloppy that to adopt this strategy, we have to potentially add support that will break something that you didn't expect. Maybe that is being too scared, it just felt a bit weird to me. 

I also don't love the idea of asserts for all of those, but recognize that most wouldn't be needed.

**Comment by pixelzoom** [comment]
Adding asserts for options that the client should not set is the way to go.  The general pattern that I've been using is:


```js
function MyType( ..., options ) {

  options = _.extend( { ... }, options );

  assert && assert( !options.something, 'MyType sets something' );
  options.something = someValue;

}
```

**Comment by zepumph** [comment]
Seems like there is consensus here. Thanks for everyone's help. I don't think there is much more to discuss, but I'll leave it on dev meeting to explain the results so that we are all on the same page about this.

**Comment by samreid** [comment]
@zepumph can you please also document the consensus pattern in phet-info/docs/phet-software-design-patterns.md ?

**Comment by zepumph** [comment]
I updated `SliderUnit` in ohms law, and updated the design patterns document. Closing
