### ISSUE TITLE
Focus lost when using ESC key to close dialog (when system focus not visible on Close button)

### ISSUE THREAD

**Issue by terracoda** [phetsims/ohms-law#114]
Mentioned in #102, and moving to its own issue:
I noticed that keyboard focus is lost, "moves to Sim Resources Region" when I use the ESC key to close the Keyboard Help dialog. Focus is lost only if visual focus is not on the close button, i.e., when system focus is not visible and the virtual cursor is somewhere in the dialog's content. If I hit ESC with focus on the close button, focus is not lost. If I close the dialog with the close button, focus is not lost.

Note this issue might have been resolved in RIAW RC Testing?

Issue not present with keyboard alone as visual focus never moves off Close button.

**Platform:**
MacBook Pro, High Sierra 10.13.4
Safari 11.1
Voice Over
Tested from Master June 12 at 12 noon NT/ 8:30 am MT.

**Comment by terracoda** [comment]
@zepumph here's the issue in RIAW https://github.com/phetsims/resistance-in-a-wire/issues/143

**Comment by terracoda** [comment]
@zepumph re-assigning to @jessegreenberg. 
This is general to all sims including BASE. The fix in RIAW was verified in NVDA. Looks like it might need a little investigation with VoiceOver, too.

**Comment by jessegreenberg** [comment]
Hmm, the fix in RIAW was verified to work for both both JAWS and VoiceOver, so something different is happening in  this case.

**Comment by jessegreenberg** [comment]
Testing on Safari 11.1.1, macOS 10.13.5 - If the virtual  cursor is on the H1 or H2 in the keyboard help dialog, this bug does not happen. It only happens if escape is pressed while virtual cursor is inside the list items in the dialog.

**Comment by jessegreenberg** [comment]
This isn't related to fake inputs sent by VoiceOver. Also, I can see the focus highlight flash around the keyboard help dialog button for half a second, then it disappears.

**Comment by jessegreenberg** [comment]
If I disable the VO user setting "Synchronize keyboard focus and VoiceOver cursor" this problem goes away. So for some reason,  VO is moving the virtual cursor to the navigation bar in this case, and focus is going with it. I do see a focus event on the NavigationBar.

**Comment by jessegreenberg** [comment]
With the setting for "Synchronize keyboard focus and VoiceOver cursor" enabled, if I remove the `h2` with content "Sim Resources and Tools", the problem goes away. @terracoda any ideas why that would be the case? And why VO would try to move focus to the navigation bar in this case but not others?

**Comment by terracoda** [comment]
@jessegreenberg, I apologize for my incorrect summary of the verified platforms in https://github.com/phetsims/ohms-law/issues/114#issuecomment-396691648.

**Comment by terracoda** [comment]
@jessegreenberg, I can't find the VO setting, "Synchronize keyboard focus and VoiceOver cursor"  in MacOS High Sierra 10.13.4.

The focus behaviour is very strange, and seems to be very specific to a VO user setting. While it would be useful for me to do further investigation of what the purpose of this setting is, I don't think this issue needs to hold up RC testing for BASE or publications of any A11y sims. 

**Reasoning:**
- focus is being handled correctly in all cases, but one (virtual cursor on list item)
- when focus is not returning to Keyboard Shortcuts button, focus goes to the parent region, Sim Resources. It is not to some random place in the sim. The user can easily recover by hitting Tab or VO-Right Arrow.

I did find on the MacOS accessibility email list that this setting was introduced in 10.10.

Also, in this [Chapter 2 of this guide](https://www.apple.com/voiceover/info/guide/_1124.html)
It seems that this setting  is related to "cursor tracking". Turning cursor tracking off is meant to allow users to keep their focus is one document, while they go use a different application. It could be with synchronization off, focus does not try to synchronize and move to the parent region.

Group navigation settings may also affect focus.

There are a number of VO cursor finding shortcuts listed in [Chapter 2 of the guide](https://www.apple.com/voiceover/info/guide/_1124.html). They might be useful to explore, so copying here for future reference.
![screen shot 2018-06-13 at 11 36 48 am](https://user-images.githubusercontent.com/1902116/41356511-a12afeb0-6efe-11e8-82d1-bf545c180e10.png)

I am closing this issue, as it seems to be caused by a VoiceOver user setting.

**Comment by jessegreenberg** [comment]
Thanks so much @terracoda. The QA team  made a document to track AT quriks that we are aware of, I will add this issue to it.

**Comment by jessegreenberg** [comment]
Here is the document for reference. https://docs.google.com/document/d/1518zv6F0odExFsodShZxwTmWNQk3civuNwtQUR-rEBs/edit

**Comment by terracoda** [comment]
@jessegreenberg, thanks, and great idea from QA Team about the document.
