### ISSUE TITLE
Keyboaed Short

### ISSUE THREAD

**Issue by terracoda** [phetsims/ohms-law#115]
Mentioned in #102, and just starting its own issue.

The Keyboard Shortcuts button, does not read out as a a "pop-up" button, so I am not sure it is coded as one. It is technically a pop-up button. It pops-up a dialog, and I thought it should have an aria-haspopup="dialog", but this might need more testing.

See article from Level Access
https://www.levelaccess.com/expanding-the-use-of-the-aria-haspopup-property/

I'll close start an issue in a11y-research.

**Comment by terracoda** [comment]
@zepumph, I will close this issue until we know more about how the different values of aria-haspop works across AT.

**Comment by zepumph** [comment]
Just to confirm then, we don't want to worry about this for the upcoming releasing of ohms law, but potentially we will at a later point?

**Comment by terracoda** [comment]
@zepumph, that's right. No need to implement `aria-haspopup="dialog"` for sims right  now. I need to test its support over in a11y-research repo.

**Comment by terracoda** [comment]
And to be more clear, no need to implement `aria-haspopup` for Keyboard Shortcuts button for sims right now.
