### ISSUE TITLE
Ohm's Law simulation

### ISSUE THREAD

**Issue by assassin007027** [phetsims/ohms-law#119]
I want to add a light bulb and resistances.
I want to design like this.
![image](https://user-images.githubusercontent.com/44780499/48505545-44a72f80-e882-11e8-8e2d-2fb63d10d45d.png)

**Comment by jbphet** [comment]
CCK would probably suit the requested need well.  Assigning to @oliver-phet to provide a more complete response.

**Comment by oliver-phet** [comment]
@assassin007027 Please see PhET's Circuit Construction Kit simulation: https://phet.colorado.edu/en/simulation/circuit-construction-kit-dc

**Comment by TrustyMan** [comment]
I need simple circuit.

**Comment by TrustyMan** [comment]
![image](https://user-images.githubusercontent.com/29589220/48598199-a2c83580-e99c-11e8-9057-626f2168d076.png)
Thank you for your help.
But I want to simple simulation.
I checked your given url and that is circuit design tool.
I don't need design tool.
I need static circuit and the users able to  change Voltage and resistors.
and I want to get animation of Brightness changing.
Thank you again for your kindness.
