### ISSUE TITLE
Odd behavior on iPad

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ohms-law#122]
Here's a mention of the issue from BF in Slack:

> A note on the PhET-iO version of Ohm's Law on iPads: The page drags up and down when you try to interact with a slider (the whole sim is moving as you move a slider up and down). The sliders do work, but it's a bit disorienting

We'd like to collect data on this sim (students using it on iPad) as part of the sonification research. 
Can someone look into this and see if there might be a relatively quick solution? 

Note: The data collection window for this sim is this week to the end of march, so we likely won't have the sounds in the sim without the wrapper until data collection done or nearly done.

Mentioning @jbphet just so he's aware of this issue. Assigning @zepumph and @jessegreenberg  in case they can take a look.

**Comment by jessegreenberg** [comment]
This sounds a lot like https://github.com/phetsims/scenery/issues/770 maintenance releases were done for that issue so my guess is that version didn't get the patch.

I am not sure what the best way to fix is, whether we can do a maintenance release for that phet-io version/wrapper or release a new version (assuming that is the issue). @zepumph what do you think?

**Comment by jbphet** [comment]
I've never seen this behavior, and I'd feel a lot more confident that we had a fix if we knew how to duplicate the problem.  @emily-phet - can we get version information from the user for the sim, iPad, and iOS versions?

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/scenery/issues/770 was an issue for iOS 11.3+ and I do not see this happening with the link provided on my iPad 2 with iOS 9.3.

**Comment by emily-phet** [comment]
Just sent @jbphet BF's info so we can be added to this repo and reply directly.

**Comment by zepumph** [comment]
It may be easiest to just publish from master a new phet-io dev version of ohms law and add that to the sonification wrapper.

**Comment by BLFiedler** [comment]
iOS version 12.1.3, 9.7" iPads (model A1893) if that is useful.

**Comment by zepumph** [comment]
I published a version with OL from master over in https://github.com/phetsims/phet-io-wrapper-sonification/issues/70 and will post a link over there (since its a private repo and this is not). @BLFiedler can you test that link and see if things are working better?

**Comment by emily-phet** [comment]
@BLFiedler said it's working great. 

Thanks everyone!

Closing.
