### ISSUE TITLE
Voltage values lack precision and lead to inconsistent math

### ISSUE THREAD

**Issue by phet-steele** [phetsims/ohms-law#127]
Situations like this screenshot (were the math is incorrect due to lack of decimal places, should be 900mA) have always been possible in this sim with slow careful movement of the voltage slider. There is a huge range for each voltage value where the slider can be dragged multiple "steps" before the voltage changes. Now that we have keyboard nav, it is way easier to encounter precision errors like this (imo).

![image](https://user-images.githubusercontent.com/5863899/52895030-a45af280-3171-11e9-9fc5-39efa9270044.png)

@ariel-phet what do you think (and who is even the designer for this sim)? Should we add another decimal place? Or should we make the sliders less smooth so there are fewer snaps for each voltage? Maybe double check with @jessegreenberg that I'm even right about the cause of this.

For phetsims/QA/issues/289.

<details><summary><sup><sup>Do</sup></sup><sub><sub>not</sub></sub><sup><sup>click</sup></sup><sub><sub>me</sub></sub></summary><sub><sub>Or should we do nothing and defer another issue? I don't like this option.</sub></sub></details>

**Comment by ariel-phet** [comment]
@jessegreenberg it looks to me like the "fine" step with keyboard nav for the voltage slider is 0.1 volts 

For simplicity, I would be fine if this were a "steppy" slider with 0.1 volt increments when using a mouse. There is no real pedagogical advantage to having a perfectly smooth slider in this sim, and people like @phet-steele can find these situations where precision is competing with the calculated relationships.

**Comment by jessegreenberg** [comment]
Thanks @phet-steele and @ariel-phet, sounds good. This will probably also fix #129 for free because the positioning assumed 0.1 increments. But Ill double check.

**Comment by jessegreenberg** [comment]
Constraint added to make a "steppy" slider. Reassigning to @ariel-phet to review the feel or just close if that is best.

**Comment by ariel-phet** [comment]
@jessegreenberg looks good to me on master. Closing
