### ISSUE TITLE
Using Keyboard nav in Keyboard nav dialog causes screen to freeze with sound

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ohms-law#130]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/289
If you interact with the keyboard nav dialog using keyboard nav the screen freezes and you must refresh the page for the sim to be usable.  Some things can still be interacted with.  If you drag on the area of the sliders you will hear the noise, but it then won't stop.  If you enter keyboard nav with a mouse but exit with keyboard nav you will see this frozen behavior without the dialog up.  This shows that the focus border is also frozen, even after you hit tab and focus is somewhere else.
**Steps to reproduce:**
1. Use keyboard nav to open the keyboard nav dialog
2. Try to leave the dialog
3. Click around on page
4. Refresh page

**Screenshots:**
https://drive.google.com/file/d/1J0v1sA3J4Wpfpot9YfYjDpe11KLeBcJ7/view?usp=sharing

Troubleshooting information (do not edit):

<details>

Name: ‪Ohm's Law‬
URL: https://phet-dev.colorado.edu/html/ohms-law/1.4.0-dev.26/phet/ohms-law_en_phet.html
Version: 1.4.0-dev.26 2019-02-16 00:29:23 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
Language: en-US
Window: 1536x731
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Same happens with phet menu

**Comment by jessegreenberg** [comment]
@KatieWoe are there any errors in the console? It sounds like this may be similar to #128, can you confirm?

**Comment by KatieWoe** [comment]
Looks like.  Here's the console: 

![console](https://user-images.githubusercontent.com/41024075/52977472-9d5afc80-338a-11e9-9b6b-b03911fe5d48.jpg)

**Comment by jessegreenberg** [comment]
OK, thanks! Closing this issue then, Ill continue in #128
