### ISSUE TITLE
No sound when using Jaws

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ohms-law#133]
For https://github.com/phetsims/QA/issues/289
The sound that plays when adjusting the sliders does not seem to play when using Jaws.  Used Jaws on Win 10 chrome.  Sound did play with NVDA + Firefox.

**Comment by jessegreenberg** [comment]
Hmm, Ill take a look at some user settings maybe we can recommend something. @KatieWoe do you remember if this came up in testing RIAW?

**Comment by KatieWoe** [comment]
I don't think it did.  At least that I remember.  I can go take a second look just in case though.

**Comment by KatieWoe** [comment]
Just checked Jaws + chrome + published RIAW and sound does play when sliders are adjusted.

**Comment by jessegreenberg** [comment]
Oh how weird! Ill take a look

**Comment by jessegreenberg** [comment]
Thanks for checking, that is helpful.

**Comment by jessegreenberg** [comment]
I just checked JAWS + Chrome + OL at https://phet-dev.colorado.edu/html/ohms-law/1.4.0-dev.26/phet/ohms-law_en_phet.html and I hear sound while I use the AT. @KatieWoe can you please confirm that you don't have phet-dev muted in Chrome? Does the tab have this icon?

![image](https://user-images.githubusercontent.com/6396244/53036547-f3d94100-3445-11e9-98fd-c0371a993068.png)

**Comment by KatieWoe** [comment]
I just went to double check.  I didn't see the mute icon, but I also heard the sound.  I think there might be something wrong with my headphones, since I was wearing them when I encountered the problem and was using the computer speakers just now.  The left earpiece sometimes gives out, so if it was trying to come through there, that might be the cause.  Sorry for the confusion.  Like can be closed.

**Comment by jessegreenberg** [comment]
Ok, sounds good, we can probably close then. Then next thing I was going to ask was to try to modify this setting
![image](https://user-images.githubusercontent.com/6396244/53036916-dce71e80-3446-11e9-8f88-5660f8366f21.png)

which prevents audio. But if it was working with a different set of speakers it probably isn't related this time. Thanks @KatieWoe,closing.
