### ISSUE TITLE
Text overlap when stringTest=long

### ISSUE THREAD

**Issue by rea-laura** [phetsims/ohms-law#134]
<b>Test Device</b>

Jordan

<b>Operating System</b>

Mojave 10.14.3

<b>Browser</b>

Safari 12.0.3

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/289:
when string test = long, the voltage and resistance slider labels have overlapping text. Could potentially be caused by the overlap of the letter and label above the slider (see visuals). Could possibly be a screen resolution issue, but to me it looks overlapped.

<b>Steps to Reproduce</b>

1) open sim with ?stringTest=long
2) note that the resistance and voltage headers have overlapping strings.

<b>Visuals</b>
Overlap
![screen shot 2019-02-20 at 9 26 05 am](https://user-images.githubusercontent.com/44005544/53107465-4d974500-34f2-11e9-829a-8a2e0d53aa6a.png)

Sim without string test showing letter and label that possibly overlap when stringTest=long:
![image](https://user-images.githubusercontent.com/44005544/53108769-ce574080-34f4-11e9-8aa1-44bcf571fe72.png)

**Comment by jessegreenberg** [comment]
The VBox that aligns these pieces of text has spacing of -5, and LayoutBox has the spacing relative to the bounds of the Nodes. So if the heights of the Text is less than 5, they will overlap which is what is happening for stringTest=long.

**Comment by jessegreenberg** [comment]
You can see them just start to overlap for string just longer than double:
![image](https://user-images.githubusercontent.com/6396244/53120174-40447f80-351f-11e9-93f9-8d712088402c.png)

**Comment by KatieWoe** [comment]
Here is a bit of a clearer picture of stringTest=long
![clearerpic](https://user-images.githubusercontent.com/41024075/53120847-fbfdb300-350f-11e9-92cd-83461138ec53.jpg)

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, here it is after the above commit:
![image](https://user-images.githubusercontent.com/6396244/53121205-a8946080-3521-11e9-8024-3a47abe83d66.png)

**Comment by jessegreenberg** [comment]
OK, thanks @rea-laura, closing this issue.
