### ISSUE TITLE
Mobile VO difficulty reading bullet list

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ohms-law#135]
For https://github.com/phetsims/QA/issues/303.  Testing using iPad 2018 (6th gen) with iOS 12.  At one point, while trying to read through the scene description VO seemed to have trouble reading the bulleted lists.  This includes the section where it reads the voltage, resistance, and current as well as the section where it describes the circuit.  When it got to this point, VO stopped reading.  Using gestures you could skip past and read other parts, but the list would not read.  I have been unable to reproduce unfortunately.
At the time current was maxed out (V high and R low), but these settings have since failed to produce those results.

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe I will take a look. Over slack @KatieWoe confirmed that this was an issue once but has not been reproducible since. If it doesn't come up again after additional testing I will be OK closing this issue.

**Comment by jessegreenberg** [comment]
Thanks for making an issue @KatieWoe. I tried on an iPad Air 2 with VO ~8 times including with extreme slider values, sim resets and sim reloads and I have been able to read through the sim summary lists. I was also able to read through the whole sim automatically by swiping two fingers quickly down the screen. I think  this is OK to close for now but if you encounter this again feel free to reopen @KatieWoe.
