### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ohms-law#137]
Template for Issues: 
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* The pointer areas could all be a bit hard to grab, particularly the buttons.
* Looking at RIAW may help with the slider areas

Screenshots:
![Image from iOS](https://user-images.githubusercontent.com/41024075/55903438-de9daa80-5b8a-11e9-8812-8b45b6c92ace.png)

**Comment by arouinfar** [comment]
Thanks @KatieWoe. I believe these issues have already been addressed in the updated design of Ohm's Law, which we're in the process of redeploying. 

![image](https://user-images.githubusercontent.com/8419308/56071279-f45dcc00-5d52-11e9-810e-1465c5936cf0.png)

I'll go ahead and close this issue.
