### ISSUE TITLE
Opening "About..." dialogue can freeze sim

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/ohms-law#143]
While double checking https://github.com/phetsims/QA/issues/313, I noticed that on iOS 10 + XHTML the sim can freeze if the "About..." dialogue is opened and the links are clicked. It gives the following error:

```
[Error] TypeError: null is not an object (evaluating 'window.open(e,"_blank").focus')
    fire (ohms-law_phet.js:912:531760)
    setButtonState (ohms-law_phet.js:912:479894)
    up (ohms-law_phet.js:912:479288)
    buttonUp (ohms-law_phet.js:912:478463)
    up (ohms-law_phet.js:912:477450)
    value (ohms-law_phet.js:912:966000)
    value (ohms-law_phet.js:912:965711)
    value (ohms-law_phet.js:912:964229)
    (anonymous function) (ohms-law_phet.js:912:953523)
    value (ohms-law_phet.js:912:158529)
    value (ohms-law_phet.js:912:962400)
    run (ohms-law_phet.js:912:943459)
    value (ohms-law_phet.js:912:959925)
    value (ohms-law_phet.js:912:959643)
    batchWindowEvent (ohms-law_phet.js:912:946282)
    ontouchend (ohms-law_phet.js:912:947546)
```

@jessegreenberg, we don't support iOS 10 anymore; I'm just documenting this issue. Feel free to close once you've read this.

**Comment by jessegreenberg** [comment]
@lmulhall-phet thanks, good to know. Did you verify that this does not happen on the other iOS versions that we do support?

**Comment by jessegreenberg** [comment]
Also, it seems that this would happen for every sim, not just ohms-law.

**Comment by jessegreenberg** [comment]
I just verified that this is not happening in iOS 12.2. But this is more of a scenery issue so I am going to move it there and see if @jonathanolson has any thoughts before closing.

**Comment by jessegreenberg** [comment]
I created https://github.com/phetsims/scenery/issues/970 for this. This issue can be closed, thanks @lmulhall-phet
