### ISSUE TITLE
Wrap-up: Complete Interview Spreadsheet

### ISSUE THREAD

**Issue by terracoda** [phetsims/ohms-law#149]
@terracoda moved all Ohm's Law design files to their new location in the Multimodal Features folder, and started an interview spreadsheet here:
https://docs.google.com/spreadsheets/d/1Xye2uVrOa_4FR1HFfdH3NLXkj_cjg5ngqDsG7wOH0Z4/edit#gid=0

Reaching out to @briannatomlinson and @emily-phet to see if there are anymore interviews that need to be added as this sim nears publication with all its a11y features.

**Comment by briannatomlinson** [comment]
I'm waiting on permission to edit that file -- then I'll add them

**Comment by briannatomlinson** [comment]
Ok Done!

**Comment by terracoda** [comment]
Thanks @briannatomlinson!

**Comment by terracoda** [comment]
@emily-phet, I don't think there is anything else. Please comment or close.
