### ISSUE TITLE
Resistor dots messed up on Samsung Galaxy Tab 2

### ISSUE THREAD

**Issue by phetsims** [phetsims/ohms-law#15]
The dots on the resistor that are meant to depict resistivity are not rendered on Samsung Galaxy Tab 2.

Note: Please don't work on this one just yet (unless it is an easy fix) - PhET is going to have some internal discussions about whether support for this device is really required.

**Comment by jbphet** [comment]
Samsung Galaxy Tab 2 is no longer a supported platform, and hasn't been for a while.  Closing.
