### ISSUE TITLE
branch: soundDesignCourse

### ISSUE THREAD

**Issue by jbphet** [phetsims/ohms-law#150]
This branch is being set up as a place to work on variations of the sound design behavior needed for a sound design course that is being developed by @briannatomlinson.  The versions requested so far are listed below.  All changes are described with respect to the currently published version, which is 1.4.4.

- [x] no clicks when sliders are moved
- [x] reversed mapping of current sound, i.e. playback rate goes down and current goes up
- [x] flowing current starts off (as it does now), but once started it never fades out
- [x] same as previous, i.e. flowing current starts off but once started it never fades out, with the slider clicks turned off

**Comment by jbphet** [comment]
I've created a one-off version from this branch that supports query parameters that should allow @briannatomlinson to get the behavior she needs.  Below are links with the query parameters set as needed, at least to the best of my understanding:

+ no clicks when sliders moved: https://phet-dev.colorado.edu/html/ohms-law/1.5.0-soundDesignCourse.1/phet/ohms-law_en_phet.html?sliderClicksEnabled=false
+ reversed mapping of current to playback rate: https://phet-dev.colorado.edu/html/ohms-law/1.5.0-soundDesignCourse.1/phet/ohms-law_en_phet.html?currentSoundPlaybackMappingReversed
+ flowing current sound does not fade: https://phet-dev.colorado.edu/html/ohms-law/1.5.0-soundDesignCourse.1/phet/ohms-law_en_phet.html?currentSoundFades=false
+ flowing current sound does not fade and sliders don't click: https://phet-dev.colorado.edu/html/ohms-law/1.5.0-soundDesignCourse.1/phet/ohms-law_en_phet.html?currentSoundFades=false&sliderClicksEnabled=false

All of the newly created query parameters can be used in conjunction with one another to create other variants of desired.  The parameters are listed below, examine the links above for examples of their usage:
- `sliderClicksEnabled`, a boolean which must be set to `true` or `false` when used
- `currentSoundFades`, a boolean which must be set to `true` or `false` when used
- `currentSoundPlaybackMappingReversed`, a flag that, if present, reverses the mapping

**Comment by jbphet** [comment]
@briannatomlinson - please try the links above and let me know if these provide what you need.

**Comment by briannatomlinson** [comment]
These all look great! Just what I need for this set.

**Comment by jbphet** [comment]
Re-opening and assigning to myself so that I remember to delete the branch eventually.

**Comment by jbphet** [comment]
Marking as deferred, and I have a reminder on my calendar for three months from now to check the status.  The sound design course should be completed by then, and if it is, this branch can be deleted.

**Comment by jbphet** [comment]
My reminder went off and I just checked in with @briannatomlinson and she said that all of the videos have been recorded, so it is safe to delete the branch.

**Comment by jbphet** [comment]
Branch deleted, closing.

**Comment by jbphet** [comment]
Reopening.  This branch was restored during an effort to recover some branches that were accidentally deleted.  This one had been _intentionally_ deleted, and now needs to be re-deleted.  See https://github.com/phetsims/special-ops/issues/198.

**Comment by jbphet** [comment]
Re-deletion complete.  Closing.
