### ISSUE TITLE
Remove list structure and group semantics around Slider Controls 

### ISSUE THREAD

**Issue by terracoda** [phetsims/ohms-law#155]
In https://github.com/phetsims/ohms-law/issues/153#issuecomment-583515016, I noted there was a coding error and in https://github.com/phetsims/ohms-law/issues/153#issuecomment-583528576 I also noticed there were some focus issues when using Home and End keys on the sliders when VO is enabled.

> I am finding some focus inconsistencies on the list of slider controls, so I think it may be best to remove the list structure all together around the sliders and also remove the `aria-labelledby` that creates the group semantics as we did in GFL and GFLB. I think there was some weird issues with the sliders and lists and group semantics. Let me if your memory is different, I am wrong about this.

@zepumph assigning to you to remove the list and group semantics for the slider controls. Please re-assign if you have questions or if your recollection for the sliders in GFL and GFLB is different.

**Comment by terracoda** [comment]
@zepumph, I can't find the issue in GFLB or GFL where we made the decision to remove the list structure and group semantics on the sliders. Could you post it here if you thin it is important.

**Comment by terracoda** [comment]
Found https://github.com/phetsims/gravity-force-lab/issues/187 while looking for something else.

**Comment by zepumph** [comment]
I removed the aria-labelledby association and the `li` container tags (replacing for divs). How does that look?

**Comment by zepumph** [comment]
Pinging here for a review before moving further for this sim.

**Comment by terracoda** [comment]
The sliders sound good and the pdom looks great. Thanks @zepumph. I think this issue is done.

**Comment by terracoda** [comment]
Back to you for @zepumph for closing.
