### ISSUE TITLE
Artifacts occur sometimes around the "R"

### ISSUE THREAD

**Issue by jbphet** [phetsims/ohms-law#26]
See the screen shot.  JO will probably need to look at this.

![ol-with-artifacts-from-r-character](https://f.cloud.github.com/assets/3082831/940147/22238e76-0125-11e3-9b26-d63b0238ad9c.png)

**Comment by BryceAG** [comment]
Still occurs on Win 7 IE, but not firefox or chrome

**Comment by elisemorgan** [comment]
This issue is reproducible on OS 10.10.5 Safari 9.0.3 (10601.4.4)

**Comment by BryceAG** [comment]
Reproduced on Win 8 IE but not FF or chrome. Also will happen to all characters if tested with parameter ?stringTest=R

**Comment by jbphet** [comment]
A similar issue was seen in Gravity and Orbits, see https://github.com/phetsims/gravity-and-orbits/issues/57.  The recommended solution in that case was to add an invisible rectangle to the node with bounds that are a bit larger than the node that is leaving the artifacts in order to trick the browser into re-rendering a larger area.  I'm going to give that a shot.

**Comment by jbphet** [comment]
In https://github.com/phetsims/tasks/issues/521, @phet-steele said:

> @jbphet artifacts resolved on IE11, and Menu problem resolved in Edge 25.

Closing.
