### ISSUE TITLE
sim doesn't follow convention of using single quotes for strings

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ohms-law#37]
Discovered while trying to find 'red'.  This sim has 'red' and "red", and lots of other strings that use double quotes.

**Comment by ariel-phet** [comment]
marking as deferred unless easy for @jbphet to fix

**Comment by jbphet** [comment]
I just removed a few double quotes from comments, but other than that didn't see any.  My guess is that they were removed a while back when the ESLint rule that checked for this was put into play.  Looks like our work here is done.  Closing.
