### ISSUE TITLE
reduce coupling to OhmsLawModel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ohms-law#43]
There are many cases where a constructor has parameter:

`@param {OhmsLawModel} model`

... but only needs access to one or two things in the model.

For example:

`function Arrow( model, x, y, rotation )`

... only needs access to `model.currentProperty`, so a better constructor would be:

`function CurrentResistanceView( currentProperty, x, y, w )`

**Comment by ariel-phet** [comment]
mark as deferred unless easy for @jbphet to currently fix

**Comment by jessegreenberg** [comment]
Looking through the code for #49, it looks like @veillette took care of this last month.  All view types (except OhmsLawScreenView) only have access to the Properties they use.  Closing, thanks @veillette!
