### ISSUE TITLE
Simulation is unresponsive on Microsoft Edge

### ISSUE THREAD

**Issue by bryo5363** [phetsims/ohms-law#46]
Test device: Acer Aspire R13 (Bryan's Personal Computer)

Operating System: Windows 10 64-bit

Browser: Microsoft Edge 25.10586.0.0

Problem description: The simulation does not work for Microsoft Edge. Once the user interacts with the sliders, the simulation immediately becomes unresponsive. Moreover, the Voltage and Resistance characters experience some unusual manipulation; the characters become very enlarged when making small adjustments. 

Steps to reproduce:
1) open sim
2) drag sliders. the simulation will no longer work

Severity: High

Screenshots: 
<img width="919" alt="ohm s_law" src="https://cloud.githubusercontent.com/assets/7717368/12332876/39b73fa2-baae-11e5-885a-e362b23fd3e9.PNG">

Troubleshooting information (do not edit):

Name: Ohm's Law

URL: http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.2.0/ohms-law_en.html

Version: 1.2.0

Features missing: touch

Flags: pointerEnabled, pixelRatioScaling

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586

Language: en-US

Window: 1280x603

Pixel Ratio: 1.5/1

WebGL: WebGL 0.96

GLSL: WebGL GLSL ES 0.96

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

**Comment by ariel-phet** [comment]
Will be curious if when publishing off redeploy shas this issue is resolved.

**Comment by jbphet** [comment]
This sim was published before the Edge browser existed, and there were a number of things done in Scenery and other libraries to make PhET sims work, so it's not too surprising that the simulation have problems.  I just tested using the latest versions of all libs, and the sim works fine on Edge.  This will, of course, need to be tested on the next release.

**Comment by jbphet** [comment]
The 1.3.0 release candidates have been tested on Edge and the sim is responsive.  Closing.
