### ISSUE TITLE
Issues with Double, Long, rtl String Tests

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/ohms-law#47]
Related to https://github.com/phetsims/tasks/issues/479 

Test device: Personal Mac

Operating System: OS X 10.10.5

Browser: Chrome 47.0.2526.106

Problem description: Funky with double, long, rtl strings

Steps to reproduce: Perform string tests

Severity:

Screenshots:
Double:
![screen shot 2016-01-15 at 1 12 42 pm](https://cloud.githubusercontent.com/assets/12610678/12364169/67b7e44c-bb8a-11e5-9340-5fa3090aa75d.jpg)

Long:
![screen shot 2016-01-15 at 1 13 53 pm](https://cloud.githubusercontent.com/assets/12610678/12364185/71f09d3c-bb8a-11e5-88c6-5f8ac8b397ca.jpg)

rtl:
![screen shot 2016-01-15 at 1 14 20 pm](https://cloud.githubusercontent.com/assets/12610678/12364189/78a80098-bb8a-11e5-8fb6-0c994c52c199.jpg)

Troubleshooting information (do not edit):
Name: ‪Ohm's Law‬
URL: http://phettest.colorado.edu/ohms-law/ohms-law_en.html?ea&brand=phet
Version: 1.2.0-dev.2 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
Language: en-US
Window: 1268x653
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by jbphet** [comment]
This should now be fixed, and I'll make sure it gets tested on either the next dev or RC release.

**Comment by elisemorgan** [comment]
This issue is resolved
