### ISSUE TITLE
Is too much of OhmsLawScreenView.js empirically determined?

### ISSUE THREAD

**Issue by zepumph** [phetsims/ohms-law#55]
There are 5 "empirically determined" values in the screen view effecting 3/5 view components in the sim. Is this too much? Should sims have a more robust layout scheme, even when the layout is static? Should effort be taken to minimize this? I'm not sure how to, but if someone recognizes it as a problem, I would be happy to pair for some advice on tackling the problem.

Assigning to @ariel-phet. Could you please determine an experienced developer that is not overbooked currently that may be able to take 5-30 minutes to help me with this issue. Thanks!

**Comment by ariel-phet** [comment]
@jessegreenberg would be a good person. It should be noted that this sim was pretty early in HTML5 land, and was originally done by MLL, so it could likely benefit from multiple improvements.

**Comment by zepumph** [comment]
>could likely benefit from multiple improvements.

I'm not the best guy to determine exactly where these should be, but I will make issues with my best guesses. Should I ask @jessegreenberg to clarify all of the potential shortcomings?

**Comment by ariel-phet** [comment]
I would say the code review checklist should be a pretty good start....if the sim conforms well to the checklist and our style guidelines that is pretty solid.

**Comment by zepumph** [comment]
Alright, that sounds good. @jbphet did a substantial amount of work on it about 18 months ago. That combined with @veillette's work in May has made it pretty good already.

**Comment by jessegreenberg** [comment]
@zepumph, happy to look into this with you, but "empirically determined" layout values are actually common in most ScreenView types.  We don't usually model the view layout for UI components.  For instance ```MoleculesAndLightScreenView``` and ```NeuronScreenView``` have similarly documented values.

A common layout strategy for PhET is to place things in the view relative to other things, like the ```ResetAllButton``` in ohms-law is placed relative to the control panel.

**Comment by zepumph** [comment]
Sounds great thanks!

**Comment by zepumph** [comment]
from code review: https://github.com/phetsims/ohms-law/issues/51
