### ISSUE TITLE
Update Screenshot?

### ISSUE THREAD

**Issue by zepumph** [phetsims/ohms-law#59]
It seems like we need a new screenshot here. I updated the slider thumbs, and the right angle arrows match the 'I' in the formula instead of the resistor now. Here is what master looks like. @phet-steele how should I go about getting this updated?

![image](https://user-images.githubusercontent.com/6856943/27514123-5108abd6-592d-11e7-9db4-eba6497b5724.png)

**Comment by zepumph** [comment]
from code review: https://github.com/phetsims/ohms-law/issues/51

**Comment by phet-steele** [comment]
@zepumph screenshots need to be taken on a retina iPad (I do this on one we have in the office). From there, they are resized to be exactly 1248x1344. Then, they are checked in to master and any relevant production branch. The easiest way to update the screenshot is to do a maintenance (or brand new) release after it has been checked in.

So, I'd be willing to take a screenshot for this sim. What branches would need it? 1.3 and master? Are we doing a maintenance release soon from 1.3?

**Comment by zepumph** [comment]
Just master is good, after thinking a bit more. This would probably be good to do after RC testing, just in case things change a bit. I would hate for you to have to do it twice.

**Comment by phet-steele** [comment]
> This would probably be good to do after RC testing, just in case things change a bit.

They are usually done right before release anyway so I can wait!

**Comment by zepumph** [comment]
On hold until we are going to publish new versions

**Comment by KatieWoe** [comment]
This is now in RC (https://github.com/phetsims/QA/issues/313), so I think it is a good idea to take off hold and do now.  @zepumph do you agree?

**Comment by zepumph** [comment]
Yes sounds good.

**Comment by KatieWoe** [comment]
@arouinfar I matched the numerical values of the screenshots, but the sizes of the equation are different.  Are these the screenshots you want?
![ohms-law-screenshot](https://user-images.githubusercontent.com/41024075/57096125-b7418580-6cd1-11e9-8c92-7b30da7a2559.png)
![ohms-law-screenshot-alt1](https://user-images.githubusercontent.com/41024075/57096126-b7418580-6cd1-11e9-9003-723a07753b27.png)

**Comment by arouinfar** [comment]
Those look good to me @KatieWoe, thanks!

**Comment by KatieWoe** [comment]
That should do it @arouinfar and @zepumph

**Comment by arouinfar** [comment]
Thanks @KatieWoe, looks good!
