### ISSUE TITLE
Mockup for Keyboard Nav Dialog

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ohms-law#61]
(same as needed for Resistance in a Wire) 
Need customized keyboard nav help dialog. Should include two sections (note: wording not refined) with content for:

Sliders
Arrow keys move slider
Shift + arrow keys, Smaller step size modifier (Resistance)
FN + arrow keys, Larger step size modifier
PG Up/Pg Dn Jumps to slider min/max

General [this is same as in other sims]
Tab key forward
Shift-Tab backward
Esc closes dialog

Should follow same design as latest BASE dialog, regarding capitalization, bold font, etc.

**Comment by arouinfar** [comment]
@emily-phet here are two possible layouts. The text will still some adjusting, I'm sure. :)
![image](https://user-images.githubusercontent.com/8419308/28133645-e9cddf5c-66fd-11e7-8728-16549884709d.png)
![image](https://user-images.githubusercontent.com/8419308/28133712-16378a70-66fe-11e7-8a10-028cbaf874de.png)

**Comment by jessegreenberg** [comment]
@arouinfar I personally like the top layout best!

@mbarlow12 and I were looking at this, and were wondering how to best include home/end/page up/page down and function keys.

Moving in larger steps is actually not tied to the function key, it is tied to page up/page down. The function key might not be used at all for desktop or large laptop keyboards. But @mbarlow12 brought up a good point that without function, some might not be able to find those keys at all if they aren't aware that function is how you access them on compact keyboards.  But listing function key is technically not correct.  @emily-phet @arouinfar any thoughts on how this should be handled?

**Comment by jessegreenberg** [comment]
Also, in the above mockups, page up/page down will need to be replaced with end/home.

**Comment by jessegreenberg** [comment]
There was a recommendation to add an icon that indicates that shift and function are modifier keys.

One idea was to add a small icon of the arrow keys next to the modifier keys.  The small arrow key icon could be inserted into the main arrow key description do define the icon for later use.

**Comment by jessegreenberg** [comment]
We agreed to remove the function key and replace with home/end.  Also to clarify that page up/page down/ home/ end are not modifier keys, they stand alone.  Shift is the only modifier key in this group.

**Comment by jessegreenberg** [comment]
There is a group preference for the vertical layout.  There was a suggestion to add some more white space to separate and group the content.

**Comment by arouinfar** [comment]
Thanks for the feedback @jessegreenberg! I'll reassign myself to adjust the mockups. For clarification, which layout in https://github.com/phetsims/ohms-law/issues/61#issuecomment-314857680 are you referring to as the "vertical" one?

**Comment by jessegreenberg** [comment]
Thanks @arouinfar.  Sorry, I meant the second layout in https://github.com/phetsims/ohms-law/issues/61#issuecomment-314857680, thanks for clarifying.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg. I have this issue on my to-do list for this afternoon.

**Comment by zepumph** [comment]
As we are designing these, it may be nice to see some other examples, here is one I just stumbled across for slack:
![image](https://user-images.githubusercontent.com/6856943/28729033-745b1b32-7377-11e7-8fae-cc7adf9e9645.png)

**Comment by arouinfar** [comment]
Thanks for sharing the example @zepumph. The current mockups are in the style used for John Tavoltage (see https://github.com/phetsims/john-travoltage/issues/127) and BASE (see https://github.com/phetsims/balloons-and-static-electricity/issues/263), but if the team would like to have a more global discussion about style I would happy to work on more mockups. However, I think whatever decision we make should apply to all keyboard dialogs.

@jessegreenberg can you confirm that these are the correct keyboard commands:
* Home/End: move in large steps
* PG Up/Pg Dn: move to min/max

**Comment by jessegreenberg** [comment]
Almost, should be the other way around:

Home/End: move to min/max
PG Up/Pg Dn: move in large steps

**Comment by mbarlow12** [comment]
One consideration that the example above brings up is how we may deal with layouts for more complex sims.  The compact design might allow us to describe trickier/more nuanced sim interactions.

**Comment by zepumph** [comment]
I agree. It seems like decreasing the size of the icons will be key in getting more into the dialog. I'm not sure how much effort should go into this now, as I like the designs that @arouinfar is coming up with, and I think they work well for simpler sims like RIAW/OL.

**Comment by arouinfar** [comment]
I've made the changes described by @jessegreenberg using our current layout.
![image](https://user-images.githubusercontent.com/8419308/28792171-efae9dce-75eb-11e7-88c5-2a515e6f2eb9.png)

I also mocked something up more in the style of the Slack keyboard shortcut dialog. A few notable differences here would be that the description strings are generally shorter and the keys are slightly less key-like. Overall, the design is much more compact which, as @mbarlow12 pointed out, may be advantageous for more complex sims.
![image](https://user-images.githubusercontent.com/8419308/28792185-fe2c3050-75eb-11e7-8518-0aadccc6b327.png)

**Comment by zepumph** [comment]
@arouinfar that looks awesome! Even if we don't go with it, it's cool to see another strategy in the phet style.

**Comment by jessegreenberg** [comment]
@arouinfar those look great.  I prefer the second style, it does give us much more room for when we have complex sims.  I also find it easier to find the information I am looking for since there is less text to skim through ("Move in smaller steps" vs. "Hold down shift key and press arrow key to move in smaller steps").

However, the second style will probably need some supplemental a11y description for the icons which is built into the text in the top dialog.

**Comment by terracoda** [comment]
@arouinfar and @jessegreenberg, I agree that the compact version is very nice and easy to scan. However, nicely readable content for what the key icons represent would need to be provided for non-visual users.

In the non-compact version, all text content is available, and all text content is showing.

If the descriptions are in front of the visuals, non-visual access might sound like this:

**Slider Controls**
- Adjust the sliders colon Arrow keys.
- Move in smaller steps colon Shift key plus Arrows keys.
- Move in larger steps colon Page Up key or Page Down key.
- Move to end colon Home key or End key.

**General Navigation**
- Move to next item colon Tab key.
- Move to previous item colon Shift key plus Tab key.
- Exit a dialog colon Escape key.

This might be perfectly acceptable to blind users. I personally would prefer the word "with" to "colon" and fewer instances of the word "key". It is possible that the word "key" may not be necessary with some keys. Here's another non-visual example.

**Slider Controls**
- Adjust the sliders with Arrow keys.
- Move in smaller steps with Shift plus Arrows keys.
- Move in larger steps with Page Up or Page Down.
- Move to end with Home or End.

**General Navigation**
- Move to next item with Tab key.
- Move to previous item with Shift plus Tab key.
- Exit a dialog with Escape.

**Comment by terracoda** [comment]
I also was wondering about "smaller steps" and "larger steps". Since this varies between sims, does it make sense to use "smallest steps" and "largest steps"?

**Comment by terracoda** [comment]
@jessegreenberg, how are the icon images for the dialogs implemented? Are the icons actual images, svg images, or styled-up text? Alt text on images, usually includes a reference that the text is representing and "image" along with the provided alternative text.

If all the instructive text is provided (i.e. verbose version) the images do not require alternative text, and should be completely skipped by screen reader software with a blank/null `alt` attribute.

**Comment by terracoda** [comment]
@arouinfar, I prefer the side by side layouts, and agree with @jessegreenberg and @mbarlow12 that modifier keys should be clearly represented in the design.

**Comment by jessegreenberg** [comment]
The icons are drawn with Scenery like the rest of the sim, they aren't images.  I wasn't thinking that alt text would apply here. The icons and text will be invisible to the screen reader until they have representation in the parallel DOM.

**Comment by terracoda** [comment]
@arouinfar, I also think all of these mock-ups are excellent. Very nice work!

**Comment by zepumph** [comment]
>Move to end with Home or End.

What about move to "extremes" or "max/min," since you they don't do the same action. A few other suggestions too:
* "Move to extremes with Home or End"
* "Move to min/max with Home or End"
* "Move to ends with Home or End"
* "Move to the ends with Home or End"
* "Move to either end with Home or End"

**Comment by terracoda** [comment]
@jessegreenberg, thanks for clarifying. We basically have two versions then, and we can tweak the text in the PDOM so it sounds nice.

**Comment by terracoda** [comment]
@zepumph, I also was wondering about Home/END
- "Move to beginning or end with Home or End keys."

**Comment by jessegreenberg** [comment]
Regarding https://github.com/phetsims/ohms-law/issues/61#issuecomment-319421452

I agree, or we could just have two entries, one for home and end
>Move to the start: ```Home```
>Move to the end: ```End```

**Comment by terracoda** [comment]
@jessegreenberg, I prefer two entries.

**Comment by terracoda** [comment]
Re my long comparison comment (https://github.com/phetsims/ohms-law/issues/61#issuecomment-319414833). I was mainly trying to point out that we want the content to read well for both visual users and non-visual users.

It is handy, but not necessary that the text on the visual page be what we hear in the non-visual version.

**Comment by arouinfar** [comment]
Thanks for the feedback @terracoda @jessegreenberg @zepumph!

> I also was wondering about "smaller steps" and "larger steps". Since this varies between sims, does it make sense to use "smallest steps" and "largest steps"?

Good question @terracoda. I chose "smaller" and "larger" because I was describing the step size relative to the default. To me, "smallest" and "largest" implies the smallest or largest possible step size. I suppose this would be accurate for Shit+arrows, but the largest possible step would technically be home/end.

> agree with @jessegreenberg and @mbarlow12 that modifier keys should be clearly represented in the design.

Are the mockups still missing something? Isn't the "Shift" in Shift+Arrows the modifier? Let me know, and I can add whatever's missing.

> What about move to "extremes" or "max/min," since you they (both keys) don't do the same action. A few other suggestions too:

Great idea @zepumph! I'll go with @jessegreenberg's suggestion in https://github.com/phetsims/ohms-law/issues/61#issuecomment-319422708.

> Re my long comparison comment (#61 (comment)). I was mainly trying to point out that we want the content to read well for both visual users and non-visual users.It is handy, but not necessary that the text on the visual page be what we hear in the non-visual version.

Thanks for the clarification @terracoda! I think it's important to keep in mind how a non-visual user would interact with the keyboard dialog. The goal here is to find a design that can be used across all sims, some of which will have more complex keyboard interactions better suited to the less-verbose style. It's good to know that we can still communicate more to the non-visual users through the PDOM.

**Comment by mbarlow12** [comment]
> Are the mockups still missing something? Isn't the "Shift" in Shift+Arrows the modifier? Let me know, and I can add whatever's missing.
@arouinfar I think the last modifier key is **fn** and indicating that it modifies the arrows to produce pg up/dn & home/end interactions.

I was also wondering if we might want to move the broader discussion of dialog design/copy/etc to the a11y research repo?

**Comment by jessegreenberg** [comment]
> I was also wondering if we might want to move the broader discussion of dialog design/copy/etc to the a11y research repo?

That is a great idea.  I am also wondering if there is enough to consider here to start a design doc to avoid a github megathread.  @arouinfar @emily-phet @terracoda what do you think?

**Comment by terracoda** [comment]
I also, like the idea of a design document where we can clearly communicate the challenges and strategies for the visual design, and the challenges and strategies for the text-based non-visual design.

@emily-phet, @arouinfar and I iterated several times for the BASE dialog, trying to get it just right for both audiences.

**Comment by arouinfar** [comment]
Thanks for the clarification @mbarlow12!

I'll create a design doc for the Keyboard Dialog, and send out a link.

@terracoda can you remind me of where the BASE dialog doc lives? I didn't see it in PhET Accessibility > Keyboard Navigation.

**Comment by terracoda** [comment]
@arouinfar, it's in the Description Work/BASE folder
[BASE: Keyboard Shortcuts](https://docs.google.com/document/d/1vk8_N3GuyC0o_Nl8HpBUu0tvVuWyWQ8FiksexPs_qBk/edit)

**Comment by jessegreenberg** [comment]
@emily-phet suggested that we ask the IDRC to host a design crit on these designs. This will be on hold until we discuss that with them.

**Comment by arouinfar** [comment]
While I know we're still having a broader discussion about the dialog design, I believe the mockups in https://github.com/phetsims/ohms-law/issues/61#issuecomment-319157102 should be all that's needed for now (mockup-wise), so unassigning myself.

**Comment by arouinfar** [comment]
@terracoda should the Ohm's Law dialog match the design for Resistance in a Wire (https://github.com/phetsims/resistance-in-a-wire/issues/104)?

Let's pretend the underlying screenshot is Ohm's Law :)
![31189964-efa2af76-a8f6-11e7-9c13-803665ac932e](https://user-images.githubusercontent.com/8419308/31199730-9174ae9e-a915-11e7-8273-f190517aaa5c.png)

**Comment by terracoda** [comment]
@arouinfar, I think it works.

**Comment by terracoda** [comment]
@arouinfar, dialogs for both OL's and RIAW look like they are ready. Un-assigning myself and assigning back to you. Hope that's ok :-)

**Comment by arouinfar** [comment]
Thanks @terracoda! I'll reassign to @jessegreenberg for implementation (or reassignment to the appropriate dev).

**Comment by jessegreenberg** [comment]
Thanks! We are on it.

**Comment by terracoda** [comment]
@arouinfar, and @jessegreenberg, so I didn't notice this before, but it might make sense to have the arrow key images in a different order?

**Two reasons to re-think this a little:**
1. Arrows are paired fro slider movement - Left and Down move to smaller values on a slider, and Right and Up move to bigger values on a slider.
2. In many sims we will have 4-way movement and we will also have the WASD keys listed, and just wondering if we should consider that order at all? Or if we need 2 different representations.

We can discuss number 2 in the Friction issue https://github.com/phetsims/friction/issues/45

Again, sorry I didn't think of this earlier.

**Comment by terracoda** [comment]
If we have 2 different representations of the Arrow keys, I would suggest that for 2-way sliders the order be: Left Down Up Right.

**Comment by jessegreenberg** [comment]
No strong preference personally, no problems changing the order of the slider arrows. Hopefully this representation can be applicable to 4-way movement with the arrow keys as well, but that might not be possible.

**Comment by terracoda** [comment]
Well, that's the muddy bit, because the popular WASD ("wasdee") order is actually Up, Left, Down, Right.

**Comment by jessegreenberg** [comment]
To me, the arrow key icons look like they represent the arrow keys all together and I don't  know that users will really find the order to be helpful information.

**Comment by terracoda** [comment]
Well, I only think the order matters if we have to put visual representations of Arrow keys and WASD keys side by side.

**Comment by terracoda** [comment]
@arouinfar, how about we just keep things simple for now, and use the WASD order for arrow keys representations for now. That way, when the arrow keys icon is next to the WSAD key icon, they will represent the same direction in the same order.

WASD key order is Up Left Down Right.

**Comment by arouinfar** [comment]
Sounds good @terracoda. I think it makes sense to use the WASD order.

Here's an updated mockup for Ohm's Law using the WASD ordering for the arrow keys.
![screen shot 2017-10-06 at 11 22 06 am](https://user-images.githubusercontent.com/8419308/31290148-a008474e-aa88-11e7-95ad-e0bff63771c2.png)

**Comment by terracoda** [comment]
Ok, looks almost the same and just as good!
Thanks @arouinfar.

@jessegreenberg, we should be good to implement now.

**Comment by jessegreenberg** [comment]
> Well, I only think the order matters if we have to put visual representations of Arrow keys and WASD keys side by side.

Yes, that is a good point @terracoda.

**Comment by jessegreenberg** [comment]
@terracoda @emily-phet @arouinfar can you please review? It is the same as resistance-in-a-wire.
![capture](https://user-images.githubusercontent.com/6396244/31302193-05ad155a-aabd-11e7-8c3b-a43ce1946cf8.PNG)

http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.4.0-dev.13/ohms-law_en.html?accessibility

Any pixel polishing?

**Comment by emily-phet** [comment]
@jessegreenberg Beautiful! Looks ready to go to me.

**Comment by arouinfar** [comment]
Looks great @jessegreenberg!

**Comment by terracoda** [comment]
@jessegreenberg, I agree. It looks great.

**Comment by jessegreenberg** [comment]
Thanks all, closing this issue.

**Comment by terracoda** [comment]
Note change to slider representation as described in https://github.com/phetsims/resistance-in-a-wire/issues/104 for Resistance in a Wire.

**Comment by arouinfar** [comment]
@jessegreenberg I think you can migrate the redesigned dialog for RIAW to Ohm's Law too.

**Comment by arouinfar** [comment]
The tweaks to the slider controls section decribed in https://github.com/phetsims/resistance-in-a-wire/issues/104#issuecomment-337305901 will also apply to Ohm's Law. 

Sorry for all of the design requests @jessegreenberg! This should be the last round of changes. Moving forward, the slider controls section will contain the same content (though headings may differ).

**Comment by jessegreenberg** [comment]
Not a problem, thanks for the improvements @arouinfar and @terracoda!  The changes @zepumph made for this dialog were handled in scenery-phet so the dialog should already be updated. From master:

![image](https://user-images.githubusercontent.com/6396244/31733321-8b9fa7f6-b3f8-11e7-829b-598c6ae4c4ea.png)

@arouinfar can you please verify that this issue can be closed?

**Comment by arouinfar** [comment]
Looks great @jessegreenberg. Thanks!!
