### ISSUE TITLE
Screen layout is scaled way too high

### ISSUE THREAD

**Issue by phet-steele** [phetsims/ohms-law#62]
Somewhere down the road (between the release of 1.2.0 and 1.3.0), the layout of many things on the screen changed.

1.2.0 (the good one)
<img width="1920" alt="screen shot 2017-07-12 at 11 37 06 am" src="https://user-images.githubusercontent.com/5863899/28131234-831035b4-66f6-11e7-927d-c1d670da0b96.png">

Every version 1.3.0+
<img width="1920" alt="screen shot 2017-07-12 at 11 37 19 am" src="https://user-images.githubusercontent.com/5863899/28131237-86f54d04-66f6-11e7-8041-da1406d07063.png">

Generally, it looks like the entire screen was "zoomed in" causing everything to be larger and:

- The equation and circuit (all parts of it)  are shifted down to the left
- The panel and the buttons below are shifted right and up

@zepumph, myself and @ariel-phet recommend changing the screen layout back to its original size (like that of 1.2.0).

For phetsims/QA/issues/18.

**Comment by zepumph** [comment]
I took a first pass at working on the layout. Most of the sim's layout is hardcoded, and after talking with @jonathanolson and @jessegreenberg, I ended up getting some great help converting it to a more dynamic layout. It is in a branch, just in case we decide to go a different way. 

It's not perfectly the same at all, but I want to get feedback on it before continuing. I also found it helpful to use the ?dev parameter to look at screen bounds.

http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.4.0-dev.1/ohms-law_en.html

https://phet.colorado.edu/sims/html/ohms-law/1.2.0/ohms-law_en.html?dev


assigning to @ariel-phet and @phet-steele for comments.

**Comment by phet-steele** [comment]
@zepumph, most of this is looking great! There are little things that are different, like the initial scaling of some of the letters. I'll defer to @ariel-phet on how important the differences are.

My question, why are the `?dev` bounds different between the two versions?

**Comment by zepumph** [comment]
>My question, why are the ?dev bounds different between the two versions?

I deliberated on this with @jessegreenberg and he seemed to think that it was because 1.2 was published before we had a default screen layout bounds for all sims. I bet that at one point the OL layout bounds were changed to use this new default. I would even say that I think that this is where this issue's root problem came from. No matter it has been good to go back and improve OL's layout. It seems like it has been a long time coming.

**Comment by zepumph** [comment]
I'm working on it a bit more this afternoon. I will make another dev version in a few hours. I already changed a few things to make the versions even closer.

**Comment by zepumph** [comment]
@ariel-phet at some point I would love to chat about this, because there may be a line that we don't wish to cross in terms of getting it to be exactly like 1.2 vs cost to do it. Currently I'm just improving layout approach, so I don't think we are there yet.

**Comment by ariel-phet** [comment]
@zepumph no need for it to be exactly the same. Close enough will be good enough for this sim.

**Comment by zepumph** [comment]
http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.4.0-dev.2/ohms-law_en.html

Could you confirm that this is "close enough" and you can close. I will merge into master now.

**Comment by ariel-phet** [comment]
Looking good 🥇
