### ISSUE TITLE
batterText typo

### ISSUE THREAD

**Issue by phet-steele** [phetsims/ohms-law#63]
Every battery text node is instrumented as `ohmsLaw.ohmsLawScreen.view.wireBox.batteriesView.battery_0.batterText`. Unless this sim is about making pancakes, it should be `batteryText` at the end, not `batterText`.

Seen on macOS 10.12.5 Chrome. For phetsims/QA/issues/18.

**Comment by zepumph** [comment]
Fixed, closing
