### ISSUE TITLE
Fails to "Launch" from Instance Proxies

### ISSUE THREAD

**Issue by phet-steele** [phetsims/ohms-law#64]
http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.4.0-phetiodev.1/wrappers/instance-proxies/instance-proxies.html?sim=ohms-law&relativeSimPath fails with this error:
```
Uncaught ReferenceError: SimIFrameClient is not defined
(anonymous) @ VM7211 instance-proxies.html?sim=ohms-law&relativeSimPath:6
```

Seen on macOS 10.12.5 Chrome. For phetsims/QA/issues/18.

**Comment by zepumph** [comment]
This was fixed as part of https://github.com/phetsims/phet-io-wrappers/issues/10 Closing
