### ISSUE TITLE
Only a few of the dots are showing when "Launch" is pressed in Instance Proxies

### ISSUE THREAD

**Issue by zepumph** [phetsims/ohms-law#66]
When you minimize the resistivity, there are about 15 dots or so, but after launching into a new tab, there are between 0 and 3 most of the time.

**Comment by zepumph** [comment]
Thanks @phet-steele for pointing it out.

**Comment by zepumph** [comment]
I see this behavior in RIAW as well, with the same implementation of dots on a wire:
![image](https://user-images.githubusercontent.com/6856943/28338300-fc225e38-6bb4-11e7-97de-02794ae3de97.png)

**Comment by zepumph** [comment]
@samreid could you weigh in on what you think may be going wrong here. I looked through the way that the group tandem is being used and nothing seemed wrong. I'm not sure where to investigate.

**Comment by samreid** [comment]
Do those dots work in the state wrapper?  Is the "save & load for dynamic particles" set up for this sim?  Or is it relying on a repeatable random number sequence?

**Comment by phet-steele** [comment]
This is for phetsims/QA/issues/24.

**Comment by phet-steele** [comment]
> Do those dots work in the state wrapper? Is the "save & load for dynamic particles" set up for this sim? Or is it relying on a repeatable random number sequence?

I'll defer to @zepumph, but I believe it's the latter (random number sequence)

**Comment by zepumph** [comment]
>Do those dots work in the state wrapper?

Kind of, they seem not to be seeded, so they are different dots. Otherwise they work as expected. Notice this zoomed in picture:
![image](https://user-images.githubusercontent.com/6856943/28431780-f7c88f82-6d31-11e7-8bd1-ff7f1f5cb702.png)


It is relying on a repeatable random number sequence. When mirror inputs seeds the random, it is exact. 
![image](https://user-images.githubusercontent.com/6856943/28431828-2e0547e8-6d32-11e7-833e-9cbdee8a338a.png)


It seems like these dots need to have a state saved slightly better. It isn't trying to save/load it's location, just pickable/visible. These are the two method calls that instance proxies 'launch' collects for each dot.

```json
{
    "phetioID": "ohmsLaw.ohmsLawScreen.view.wireBox.resistorNode.dotsNode.dot_291",
    "method": "setPickable",
    "args": [
      null
    ]
  },
  {
    "phetioID": "ohmsLaw.ohmsLawScreen.view.wireBox.resistorNode.dotsNode.dot_292",
    "method": "setVisible",
    "args": [
      false
    ]
  },
```

I think we have to figure out how to include location of these dots as well. @samreid what do you think? It seems like most nodes are assumed to be in the correct position by the sim. We may need a new TType.

**Comment by zepumph** [comment]
I talked with @samreid, and we found the problem head on. Context: there are two key pieces in the state that is being sent to the next sim, the resistanceProperty, and the dots (all 300 or so of the them). It seems like the resistance property is being set into the downstream sim first, so the link function that sets the number of dots visible  is called, and then afterwards the dots of the previous state are being set in the downstream sim. 

The problem is that since the seeds of the two sims are not aligned, the `dotsNode`'s children are being shuffled around, they don't match up to the previous sim. Here is the problemed line:
`    dotsNode.children = phet.joist.random.shuffle( dotsNode.children );`

I decided to rewrite the randomizing function so that a dot can be anywhere in the resistor, and this fixed the problem. Before they were placed them on a grid, but each one moved randomly a bit to make them look irregular. The new way is truly random. I will need to see if @ariel-phet is alright with this, technically there could be a bit more clustering and spacing, but I didn't think it was that noticeable.

@ariel-phet will you look at the dot randomization on master, and see if it looks comparable to http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.4.0-phetiodev.2/ohms-law_en-phetio.html?phetioStandalone.

**Comment by zepumph** [comment]
After talking with @samreid we found a better solution committed above.

**Comment by zepumph** [comment]
If we decide to go ahead with this strategy, we should change RIAW as well, because it has this problem too.

**Comment by ariel-phet** [comment]
@zepumph this looks good to me. Pedagogically the dots represent "dislocations" or imperfections/impurities in the crystal lattice of the wire. So being truly random is not only fine, but probably more accurate. The main idea is that high resistance means lots of imperfections/impurities. The current approach seems to get that across just fine.

**Comment by zepumph** [comment]
>So being truly random is not only fine, but probably more accurate. 

Then I'm inclined to go back to https://github.com/phetsims/ohms-law/commit/3495c57d6dbf0d3e5216bcf7c7305332d743f2cb because it is much simpler, and to me it is preferred. 

The change is so subtle I feel like we have spent enough time on it. I will go ahead and update both RIAW and OL to use this new randomization pattern.

**Comment by zepumph** [comment]
I updated both sims to simplify this code as much as possible. I tested by looking at the new densities versus older versions, and things looked good, as well as testing the launch button in instance proxies. Closing

**Comment by zepumph** [comment]
On second thought @samreid could you review before closing. Any other thoughts to add?

**Comment by samreid** [comment]
I reviewed the commits on ResistorNode.js and tested it for a minute or so and it all seems OK to me.  A different strategy for the distribution of the points is used, but it behaves qualitatively like the prior algorithm.

**Comment by zepumph** [comment]
Alright thanks, Closing.
