### ISSUE TITLE
Add QA credits

### ISSUE THREAD

**Issue by zepumph** [phetsims/ohms-law#70]
similar to https://github.com/phetsims/resistance-in-a-wire/issues/89, there are no qa credits for the current sim in master. We should add them.

**Comment by zepumph** [comment]
@phet-steele let me know if the above commit looks good.

**Comment by phet-steele** [comment]
@zepumph it's good, but we need more now. `Alex Dornan, Ethan Johnson`as well, please. You'll probably have to put a line break in there somewhere. Isn't this technically #54?

**Comment by zepumph** [comment]
Oh you're right thanks!

BTW here is what credits look like, they use MultilineText so you don't have to add new lines:
```js
   if ( credits.qualityAssurance ) {
      children.push( new MultiLineText( StringUtils.format( creditsQualityAssuranceString, '\u202a' + credits.qualityAssurance + '\u202c' ), multiLineTextOptions ) );
    }
```
