### ISSUE TITLE
Add accessible labels and descriptions

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/ohms-law#74]
From https://github.com/phetsims/a11y-research/issues/48, design documents and PDOM mockups are complete, so we are ready to start implementing.  This issue will track progress and commits.

Tagging @emily-phet @terracoda and @zepumph so they are aware.

**Comment by jessegreenberg** [comment]
Here are direct links to the design doc and PDOM:


- [Full PDOM](http://htmlpreview.github.io/?https://github.com/phetsims/a11y-research/blob/master/html-sketches/ohms-law/ohms-law-pdom.html)
- [Succinct PDOM](http://htmlpreview.github.io/?https://github.com/phetsims/a11y-research/blob/master/html-sketches/ohms-law/ohms-law-pdom-succinct.html)

**Latest version of design document is here:**
[Ohm's Law Descriptions google sheet](https://docs.google.com/spreadsheets/d/15LuKXlzkh6xHpNbWC4ujtOfz1F7FJ7tj4oUF8Jvmj-k/edit#gid=0)

**Comment by zepumph** [comment]
I made a lot of changes above. I reworked FormulaNode so that it isn't using a loop to create the Texts. This is nicer because then we can access the texts as we need to.

I implemented an approach where we are comparing the letters based on their normalized values. This works pretty well, for V and R because they share the same scale, but I think for comparisons with I we will need to adjust for the scaleM and scaleB that we are using, or we will need to find another approach. Currently it is just implemented in console.log statements. 

@jessegreenberg let me know if you have any trouble getting through my piss pour code, I was really just sketching an idea of it, we will need to refine. Hopefully we can work on this again before I leave.

**Comment by jessegreenberg** [comment]
Thanks @zepumph, this looks great and it should be much easier to access the letters.

That approach looks good, though I agree we would need to adjust the normalized value for I to avoid that case where R is smaller than I, but R is described as "Huge" and I is described as "medium size".

**Comment by jessegreenberg** [comment]
I wanted to see what it would look like to compare the sizes by comparing the height of the letter Nodes, but didn't want to alter your changes until we discussed so I committed in a branch compare-height.  To get a consistent description of the size of each letter, it will calculate the min/max height for all letters in the equation and compare each letter to that range.  It would be great to discuss the pros/cons of the two approaches sometime soon.

**Comment by jessegreenberg** [comment]
@zepumph and I discussed today, and we agreed to proceed with trying to generate the relative descriptions by comparing ratios of letter heights in the view. We weren't thrilled with a collection of comparative ranges defined in constants, but the fact that they are relative ratios (not arbitrary scalings) made us feel better.  One good thing about this is that we can have @terracoda let us know what the exact scaling factors should be in terms of relative descriptions. We will create an issue to discuss that part in particular.

**Comment by jessegreenberg** [comment]
PDOM is complete.  Alerts are next.

**Comment by jessegreenberg** [comment]
I believe descriptions are finished in Ohm's Law. Here is the latest version:

http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.4.0-dev.8/ohms-law_en.html

http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.4.0-dev.8/ohms-law-a11y-view.html

@terracoda would you please review this version?

**Comment by terracoda** [comment]
Descriptions are looking good overall in the a11y-view. Here are few issues I noticed while playing/poking around

**Using the a11y-view version with Safari 10.0.03 on Mac OS 10.12.3 (no screen reader)**
[] sliders keyboard accessible at first, but was not able to get focus on them tabbing back and forth through sim after initial interactions.
[] under State of the Sim, the items in the first list need periods at the end (sorry they were missing in design doc.)
[]  Circuit description is missing the dynamic list containing the following details:
- [[Small]] arrows pointing clockwise represent a flowing current of [[5.0]] millamps.
- [[Exactly]] [[3]] batteries show [[4.5]] volts. 
- [[A good many]] dots in resistor represent resistance. 
Oh, it's not missing, the list is not in the right place. It should be under The circuit's description.

**Using Voice Over with the first link**
[] I can't get into the sim at all. Crtl-Option-Shift-Down-Arrow takes into the web content area, VO says,  "In Ohm's Law, web content content is empty."
[] Without VO off, I can't Tab into the sim at all. My focus just moves between browser tabs.

**Using Firefox 55.0.2 64-bit (no screen reader)**
[] Still can't access sim with the Tab key using Firefox.

**Using Firefox and a11y-view**
[] In Keyboard Shortcuts dialog 4 items of content are missing from PDOM version, bold/strong text is missing around "previous item" . 
[] Text from PDOM becomes visible when Keyboard Shortcuts dialog is opened.
[] Text stays on screen after dialog is closed.
![screen shot 2017-08-20 at 21 36 31](https://user-images.githubusercontent.com/1902116/29499595-b725b3fc-85ef-11e7-872e-e39af3d8f84d.png)
![screen shot 2017-08-20 at 21 36 43](https://user-images.githubusercontent.com/1902116/29499596-baa3ffb6-85ef-11e7-9c66-f4c673ce93aa.png)

**Using Voice Over with Safari in the a11y version**
- alerts working with fronted slider values. Nice!
- same issue can't find slider controls after interaction.
- Other alerts, reset and mute sound work fine.

Likely, that's all I can do until I am back on the 30th.

**Comment by jessegreenberg** [comment]
Thanks for reviewing @terracoda!  lll investigate these issues, breaking them up into separate ones to avoid a mega thread.

**Comment by jessegreenberg** [comment]
Sorry @terracoda, regarding issues with the first link, a11y requires the ?accessibility query parameter and I forgot to add it here in the link.
http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.4.0-dev.8/ohms-law_en.html?accessibility

Hopefully keyboard navigation will work with the query param.

**Comment by jessegreenberg** [comment]
> In Keyboard Shortcuts dialog 4 items of content are missing from PDOM version, bold/strong text is missing around "previous item" .

> Text from PDOM becomes visible when Keyboard Shortcuts dialog is opened.

> Text stays on screen after dialog is closed.

These three issues were also caused by #78, verified fixed in Firefox.

**Comment by jessegreenberg** [comment]
Regarding

> In Keyboard Shortcuts dialog 4 items of content are missing from PDOM version, bold/strong text is missing around "previous item" .

Thanks, that is also true.  I haven't worked on the keyboard help dialog, and probably won't until #61 is complete. Same with the navigation bar, that probably won't be changed until designs are finished.

**Comment by jessegreenberg** [comment]
Thanks for reviewing @terracoda, sorry these issues were in there.  Here is a new version where these things should be fixed (except for content in the Dialog).

http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.4.0-dev.9/ohms-law_en.html?accessibility

http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.4.0-dev.9/ohms-law-a11y-view.html

**Comment by terracoda** [comment]
@jessegreenberg, thanks for addressing these issues. I will review asap, likely tomorrow (August 29).

**Comment by terracoda** [comment]
@jessegreenberg, the sim is working nicely.
I am creating issues for the following items:
- The reset alert is gets over-ridden by the slider alerts. This happens after sliders have changed, and then the reset button is pressed.
- I noticed that, "dot" for period is read out if the period occurs on a line by itself. "Dot" is not read out when it occurs as part of a string of text on a line. Is it possible to make the invisible PDOM wider and further off screen? This might be a good general approach. For this sim, I simply removed the periods on the short list items in the State of the Sim section.
- Mute Sound Alerts missing periods. 
- H1 for Ohm's Law is missing apostrophe.
-General suggested changes to the content and presentation of the A11y View (will put this in A11y Research repo).

**Comment by terracoda** [comment]
@jessegreenberg, there is one other important issue I forgot to put in the list. The pink focus highlights go away after I use native Voice Over Commands. Are you aware of this issue already. I thought I saw an issue about focus highlight disappearing?

**Comment by jessegreenberg** [comment]
@terracoda can you please give an example of a native VoiceOver command?

**Comment by terracoda** [comment]
Sorry, yes. VO+Command+B is a useful command that makes the sim start reading from the beginning. VO+Command+H reads next Heading.

VO keys are Control+Option.

**Comment by terracoda** [comment]
@jessegreenberg, I will start an issue for the disappearing focus highlights.

**Comment by terracoda** [comment]
@jessegreenberg and @zepumph, I think this issue is done. We are now on dev version 14. Marking as closed.
