### ISSUE TITLE
Verbose vs Succinct a11y content

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/ohms-law#75]
@terracoda @emily-phet in #74, there are two columns in the design document, a "Possible succinct version" and what looks like a "normal" column.  Should the succinct version be implemented in addition to the normal descriptions?  I thought that "succinct" option for descriptions might only apply to alerts?

We will proceed with just implementing the normal descriptions for now.

**Comment by terracoda** [comment]
@jessegreenberg, please implement the green column. The succinct version was still up for discussion. You are correct that a generalized "succinct version" for sims would apply to alerts only. I just played with a couple of versions of content, and was quite happy with both versions in the design document.

**Comment by jessegreenberg** [comment]
Sounds good @terracoda, thanks for clarifying!  We will proceed with the green column.
