### ISSUE TITLE
When should the letter size changes be announced?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/ohms-law#91]
Right now, an alert is created and sent to the screen reader every time a letter size changes.  This works OK but is problematic because of https://github.com/phetsims/ohms-law/issues/89#issuecomment-333152647 and also because it is easy for the user to get flooded with alerts when pressing and holding a letter key or using the mouse.

I think it would be an improvement to send an alert when the dragging is "done" (finger/mouse is released or arrow key is released) to fix these.  @terracoda what do you think?

**Comment by terracoda** [comment]
@jessegreenberg, in this scenario, would the user get slider values as they move the slider and then get the last slider value plus the alert when the they stop moving?

**Comment by jessegreenberg** [comment]
@terracoda yes that sounds correct. Right now we use ```aria-valuetext``` to describe the slider value and ```aria-live``` to announce the letter size alerts.  So we will have default timing for ```aria-valuetext``` and provide the rest when the user stops moving the slider.

**Comment by terracoda** [comment]
@jessegreenberg, this approach sounds like a good one to me.

**Comment by terracoda** [comment]
@jessegreenberg, sorry, I forgot to re-assign back to you, so doing that now.

**Comment by jessegreenberg** [comment]
Thanks @terracoda, done in the commits above, closing.
