### ISSUE TITLE
Added sentence to Scene Summary that indicates this is an interactive sim.

### ISSUE THREAD

**Issue by terracoda** [phetsims/ohms-law#98]
To help indicate to non-visual users that the sim's descriptions update as they interact with it, @emily-phet and I added a new sentence to the very beginning of the scene summary on Tuesday. 

We hope this intro will help users understand that they have a wealth of information available to them beyond the alerts they get while interacting. Furthermore, it sets up the the initial interaction hint option to "read on for details" a little better.

Please update the introductory Scene Summary paragraph.

**New Scene Summary Intro Paragraph**
_This is an interactive sim. Descriptions change as you play with it. It has a Play Area and Control Panel. In the Play Area you find the equation for Ohm's Law, V equals I times R, and a circuit. Voltage and resistance sliders allow changes to the equation and circuit. In the Control Panel, buttons mute sound or reset the sim._

**Changed from**
_This sim has a Play Area and Control Panel. In the Play Area you find the equation for Ohm's Law, V equals I times R, and a circuit. Voltage and resistance sliders allow changes to the equation and circuit. In the Control Panel, buttons mute sound or reset the sim._

**For the record, the interaction hint (unchanged) for this sim is:**
_Look for voltage and resistance sliders to play, or read on for details about equation and circuit._

**Comment by terracoda** [comment]
@jessegreenberg and @zepumph, I assigned you both because both the a11y sim and the phet-io sims will need this small update.

**Comment by zepumph** [comment]
Updated in the above commit to master, closing
